import assert from 'node:assert/strict';
import { addPlayer, applyAction, botAction, createGame, hostTick, removePlayer, startGame } from './poolEngine';
import { simulate } from './physics';

let game = addPlayer(createGame('ABC123', 'doubles', 3, 0), 'alice', 'Alice', 0);
game = addPlayer(game, 'bob', 'Bob', 0);
game = startGame(game, 0);
assert.deepEqual(game.players.map((p) => p.team), [0, 1, 0, 1]);
assert.equal(game.balls.length, 16);
assert.equal(game.balls.find((b) => b.n === 8)?.x, 690 + 2 * (23 + .2));
assert.equal(game.activeId, 'alice');
assert.equal(game.ballInHand, 'head');
assert.equal(game.players.filter((p) => p.id.startsWith('bot:')).length, 2);
assert.throws(() => applyAction(game, 'bob', { type: 'shot', angle: 0, power: 50, tipX: 0, tipY: 0, ball: null, pocket: null, safety: false }, 1), /not your turn/);
assert.throws(() => applyAction(game, 'alice', { type: 'place', x: 500, y: 250 }, 1), /head string/);
const first = simulate([{ n: 0, x: 245, y: 250 }, { n: 1, x: 400, y: 250 }], 0, 50, 0, 0);
assert.equal(first.firstHit, 1);
assert.ok(first.balls.every((b) => Number.isFinite(b.x) && Number.isFinite(b.y)));
const breakAction = botAction(game);
assert.equal(breakAction.type, 'shot');
game = applyAction(game, 'alice', breakAction, 1);
assert.equal(game.phase, 'aiming');
assert.equal(game.activeId, 'bob', 'legal dry break passes the turn');
assert.equal(game.teams[0].shots, 1);
game = removePlayer(game, 'bob', 2);
assert.equal(game.players.length, 4);
assert.ok(game.players.some((p) => p.team === 1 && p.id.startsWith('bot:')));
assert.ok(game.activeId?.startsWith('bot:'), 'replacement bot inherits the active turn');
for (let time = 1000; time < 60_000 && game.phase !== 'finished'; time += 1000) game = hostTick(game, time);
assert.ok(game.players.length === 4);

let doubles = createGame('DEF456', 'doubles', 3, 0);
for (const id of ['alice', 'bob', 'amy', 'ben']) doubles = addPlayer(doubles, id, id, 0);
doubles = startGame(doubles, 0);
doubles.balls = [{ n: 0, x: 800, y: 15 }, { n: 1, x: 945, y: 15 }, { n: 8, x: 600, y: 300 }];
doubles.breakShot = false;
doubles.ballInHand = null;
doubles.teams[0].group = 'solids';
doubles.teams[1].group = 'stripes';
doubles = applyAction(doubles, 'alice', { type: 'shot', angle: 0, power: 20, tipX: 0, tipY: -1, ball: 1, pocket: 2, safety: false }, 1);
assert.equal(doubles.activeId, 'amy', 'Scotch doubles passes a continuing turn to the teammate');
assert.ok(!doubles.balls.some((b) => b.n === 1));
console.log('pool engine: all checks passed');
